before_install:
- sudo wget https://www.scala-lang.org/files/archive/scala-2.12.7.deb
- sudo dpkg -i scala-2.12.7.deb
jdk:
- oraclejdk8
sudo: required
script:
- make clean compile test
notifications:
  email:
    recipients:
    - kinjacono@yahoo.co.uk
deploy:
  provider: heroku
  buildpack: jvm
  skip_cleanup: yes
  api_key:
    secure: Qgr2g5j43lFXzn/GLL2HG6qiXcsIkxMjYQgMZo8zbn1t6OczW2AlnI2wZUGfuuUnldetjufFlItmKjg301rzWSE0ZKa/WS810ZWbCmwTqHjrxzeAyKb97jeS5gSfdt3gHKnaysVnyHOqJyI2mMY5YsDwKBAvV+ebgxxfjRsW3FHIQShfYinQKFBMMOojHGtE3r0VIMkWzJD4cVBZulIhBUoGEQBfzZYYcWrwFu0zwzM7Z2psxlniEGGHpZPhDNKxygqtXx0fkXt80cU1cKYH5PoTEAgvtqtgHsAwTmjzMA0tUIHTvZauYEGBIvSUFWbE67LRD/LCmguHwWm+FlpXhK0VdbcaOdkq6lQNSHPQ5RQFAJbn4toQzEs/eP/dhtyezfVhXRoOD/1i66wNHn21ZIRPH5M8s25HJN/hClcuCZhqX64O9jffpIX3Bc2K3wQHUtPCV9uRdjfoqL5IDzGpJOpXMDPQw5UKfX2KdqMrUozWFuJaqUDUzvNTGG8zAMKrXi7Hbk2NSw8T6i3RxwdJhqryjtiniOPK2YlnPWlL5sGlRFT+5OsYwNmyX7FpERm7T+fORCxtdTEllTcmNCMsMo6k72C8MC/WiQWPX3WFeX4nQd+sb0wc3xwHfcKCZ4HKqx/fiK/OKVncSPcldh/OGB9XVsRjhpszKNWEFITJ4ZM=
  app: todo-mvp
