before_install:
- sudo wget https://www.scala-lang.org/files/archive/scala-2.12.7.deb
- sudo dpkg -i scala-2.12.7.deb
jdk:
- oraclejdk8
sudo: required
script:
- make deps compile test assemble
cache:
  directories:
  - ./lib
notifications:
  email:
    recipients:
    - kinjacono@yahoo.co.uk
deploy:
  provider: heroku
  buildpack: jvm
  skip_cleanup: true
  api_key:
    secure: 7NvvAKQD50fkPI2HIr7aWdlr6wAeJwq9xbuqFDlZ72inJD5KtzN4wy/6MK1V4thdNXIkhzyvyot2qDL+3klwqZwCAIzlTvt3PXfXgPsemFLT/zCSzzzB3xypstn1aQJL55ViAi/A6FCB5N6J7ClNj4csAEcotMILCqQwvvW3/Nva4O7OPOL0wQR+s0n62wuhF3XvHas0TQ324mwJakljbEzOYBapHv803oD7kiOAUPJLJwbZIzYCJgT0FzFqOFlXjocMJibEXX/Lr+aAtZzImtcLEXylcUWgdwBLdULyvAVfWtoJ7K9EpLzNmWmE2RvyJFRD40gq2QEAQWf85zRckk91OFOUVt8h7SpVY6czjQMxsaztKTKTbGmw3znLqVqJAKJRvOVrJS76LuvMHysbu418X6I0+H/6syt6t68ihYCUpw/fS7Wid305GDTzuYrJBqfvepqio/CnPvP9tBFEa3c/VXkWxHgD2XVKZ9TC4oc1e1PIcq4QPbOGMIcul0Oiw8+QjsQty7pIKgF8uhOBc4uLRj9N++9mu8PCdTj+y7log6N5ZVvNEMgIk00hu7GaVaFww0Dnyy1N+n184IH5zcALDENCTyhUdXATnsWaONn20SwYy1sLNEoCiA+4gYOReYrOuVX5Tk96U4Q8CIsE4xHaaEFcqayxOSWFbnULMFU=
  app: todo-mvp
